### ISSUE TITLE
Taking too long time on Huge Tables.

### ISSUE THREAD

**Issue by satishvmadala** [spapas/django_table_filtering#1]
Hey! I have a table with 1.4 Million rows. I used RequestConfig inside my view function, like this to load Data onto DjangoTables2 without filter search:

```
sales_data = SalesTable(sale.objects.all().order_by('-time'))
RequestConfig(request,paginate={'per_page': 50}).configure(sales_data)
```

This method takes almost no time to load the data and pagination also super fast. Now, i want to implement filter search on columns and used your example, which results in consuming total memory (4 GB on dev machine)  and yet too long time, sometimes crashing.

Is there a way, i achieve best of both? Speed data loading and filters? 

Thanks!

**Comment by spapas** [comment]
Hello @MVSatish this seems to be a problem of django-filter -- I've opened the carltongibson/django-filter#442 issue there to see if there's a solution. Thanks for noticing this!

**Comment by spapas** [comment]
Hello @MVSatish , finally the issue is resolved! You need to use `filter.qs` as the table data instead of just `filter` and also use `.count` instead of `|length` to count the template items! Check my latest commit to see the changes that were needed.

Best regards,
Serafeim

**Comment by satishvmadala** [comment]
@spapas Thanks! This is fantastic. :+1:
