### ISSUE TITLE
issue with loading data

### ISSUE THREAD

**Issue by oziek88** [spapas/django_table_filtering#2]
Hey man,

Love that you've put this up.  For some reason the data won't load with the page.  Whether it's the book data or my own.  I get no errors and it's registering as if I have an empty database, showing me the "Displaying 0 out of 0".  Has this been a problem for anyone in the past? perhaps something I need to tweek. I'm using django 1.10.  I appreciate any time you take helping me out.

**Comment by spapas** [comment]
Hello @oziek88, I've updated everything to latest version. Could you check if it's working? Please try adding some books first by using

```
python manage.py fill_data 1000 100 50
```

The above should output: "Created 1000 books!!"

Now, if the main search page is not working, you can go to the /admin to be sure that the books have been created and then try some of the other pages like /nofilter (displays books without filter), /filter2 or /filter_ex.

**Comment by oziek88** [comment]
works perfectly. thank you so much for the help!

**Comment by spapas** [comment]
Great! No problem :)

**Comment by oziek88** [comment]
I do have a one other small question that I think will help me out in the long run.  When running the app, django wants to pull the template from templates/books/book_list.html.  I'm unable to figure out where that command is coming from.  Do you by any chance know what segment of the code is responsible? Perhaps that's just a django-filters formatting scheme?

**Comment by spapas** [comment]
What do you mean ? It's not working ? Or is it working and you are wondering why django searches for the ``templates/books/book_list.html`` template to display the results ?

**Comment by oziek88** [comment]
I'm wondering why django searches that template. Everything works. I'm trying to see if I can tie it with django-crudbuilder, and I was curious why django wants the template in that format

**Comment by spapas** [comment]
That's how Django CBV work. Take a look at this https://www.pydanny.com/stay-with-the-django-cbv-defaults.html

**Comment by oziek88** [comment]
perfect. that's what I figured. great source
