### ISSUE TITLE
Doesnt work on latest version

### ISSUE THREAD

**Issue by gocamiot** [spapas/django_table_filtering#3]
Hey @spapas 
I like your blogs and training style. I might need to contact you for help as well.
If I clone this and run, I run into a bunch of issues. Probably depreciated stuff.
What is the possibility that you update this wonderful training material for us to work with latest?

Regards
Jakes

**Comment by spapas** [comment]
Hey @gocamiot thank you for your kind words. I upgraded this project to latest versions, hope you find it useful!

Kind regards,
Serafeim

**Comment by gocamiot** [comment]
Good morning Serafeim, 
   
  
      
   
  
    I hope you are well. 
   
  
      
   
  
    Im a newby at Django. But I understand the structure and how it goes together. I can change code to suite my needs. Ill slowly workup to more advanced. 
   
  
      
   
  
    I have a project that needs deliver in the next 30-60 days. It is not too complex with Django. 
   
  
      
   
  
    Basically a reporting project. The requirement now is a nice basic dashboard, admin, user logins etc, and then a nice menu system. Leading to tables. The tables I need to export in csv, sort, can be large, so I thought server side data, I need to sort, global serach, and then most important, do mulitple filters, like excel, on columns. You know where I can search item, pick, then another search, pick, then the filter on the database is effected, delete a filter. That is the most important part. 
   
  
      
   
  
    Can you help me with that? 
   
  
      
   
  
    It would be nice to have a template where I can specify it in the view(which fields) and it is done for me. 
   
  
      
   
  
    Thank you for coming back to me. 
   
  
      
   
  
    I will clone and try your repo again. I am looking forward to that. 
   
  
    BTW. Your blog and training is REALLY good man. You should do something for UDEMY. You that good. :) 
   
  
      
   
  
    Warm Regards 
   
  
      
   
  
    Jakes 
   
  
      
   
  
    ps. Im here 
   
   
    
   
  
      
   
  
    Im using django-slick-reporting and cannot get the template to work. 
   
  
    Menu system cannot go three levels deep. 
   
  
    Not sure if this is serverside data. 
   
  
    Keep getting errors on basic list report. 
   
  
    Lol. Im battling in the dungeons here! lol 
   
   
   
     Im using djangoOn 24/10/2023 08:42 SAST Serafeim Papastefanos ***@***.***> wrote: 
    
   
       
    
   
       
    
     
   Hey @gocamiot thank you for your kind words. I upgraded this project to latest versions, hope you find it useful! 
   Kind regards,Serafeim
