### ISSUE TITLE
Help on reporting app.

### ISSUE THREAD

**Issue by gocamiot** [spapas/django_table_filtering#4]
Good morning Serafeim,

I hope you are well.

Thank you for the help so far and your quick response.

Im a newby at Django. But I understand the structure and how it goes together. I can change code to suite my needs. Ill slowly workup to more advanced.

I have a project that needs deliver in the next 30-60 days. It is not too complex with Django.

Basically a reporting project. The requirement now is a nice basic dashboard, admin, user logins etc, and then a nice menu system. Leading to tables. The tables I need to export in csv, sort, can be large, so I thought server side data, I need to sort, global serach, and then most important, do mulitple filters, like excel, on columns. You know where I can search item, pick, then another search, pick, then the filter on the database is effected, delete a filter. That is the most important part.

Can you help me with that?

It would be nice to have a template where I can specify it in the view(which fields) and it is done for me.

I will try out this filtering example of yours.

Thank you for coming back to me.

I will clone and try your repo again. I am looking forward to that.
BTW. Your blog and training is REALLY good man. You should do something for UDEMY. You that good. :)

Warm Regards

Jakes

**Comment by spapas** [comment]
Hey @gocamiot thank you for your kind words. Unfortunately I don't have much free time right now to help you with your project.

However if you have specific questions with Django I'd recommend to either join the #django IRC channel on libera chat or the Django discord server. There are a lot of people there that will definitely help with all your problems.

Kind regards,
Serafeim
